# Generated by nuclio.export.NuclioExporter

import numpy as np
from cloudpickle import load


import mlrun


class ChurnModel(mlrun.serving.V2ModelServer):
    def load(self):
        """
        load multiple models in nested folders, churn model only
        """
        clf_model_file, extra_data = self.get_model(".pkl")
        self.model = load(open(str(clf_model_file), "rb"))
        if "cox" in extra_data.keys():
            cox_model_file = extra_data["cox"]
            self.cox_model = load(open(str(cox_model_file), "rb"))
            if "cox/km" in extra_data.keys():
                km_model_file = extra_data["cox/km"]
                self.km_model = load(open(str(km_model_file), "rb"))

    def predict(self, body):
        try:
            feats = np.asarray(body["inputs"], dtype=np.float32).reshape(-1, 23)
            result = self.model.predict(feats, validate_features=False)
            return result.tolist()
        except Exception as e:
            raise Exception("Failed to predict %s" % e)


from mlrun.runtimes import nuclio_init_hook


def init_context(context):
    nuclio_init_hook(context, globals(), "serving_v2")


def handler(context, event):
    return context.mlrun_handler(context, event)
