# Generated by nuclio.export.NuclioExporter

import nuclio
from nuclio import build_file
import json
import pickle
from test import init_context, handler

context = nuclio.Context()
event = nuclio.Event(body=json.dumps(['John loves Mary']))
init_context(context)
outputs = pickle.loads(handler(context, event))

print(f'embeddings per token shape: {outputs[0].shape}, pooled embeddings shape: {outputs[1].shape}')

from mlrun import code_to_function
fn = code_to_function("bert_embeddings", kind="nuclio",
                      description="Get BERT based embeddings for given text",
                      categories=["NLP", "BERT", "embeddings"],
                      labels = {"author": "roye", "framework": "pytorch"},
                      code_output='.')

fn.export("function.yaml")

addr = fn.deploy(project='nlp-servers')

import requests


event_data = ['the quick brown fox jumps over the lazy dog', 'Hello I am Jacob']
resp = requests.post(addr, json=json.dumps(event_data))

output_embeddings = pickle.loads(resp.content)

print(f'embeddings per token shape: {output_embeddings[0].shape}, pooled embeddings shape: {output_embeddings[1].shape}')

