# Copyright 2019 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by nuclio.export.NuclioExporter

import pandas as pd
import pandas_profiling

from mlrun.execution import MLClientCtx
from mlrun.datastore import DataItem


def pandas_profiling_report(
    context: MLClientCtx,
    data: DataItem,
) -> None:
    """Create a Pandas Profiling Report for a dataset.
    :param context:         the function context
    :param data:            Dataset to create report for
    """

    df = data.as_df()

    profile = df.profile_report(title="Pandas Profiling Report")

    context.log_artifact(
        "Pandas Profiling Report",
        body=profile.to_html(),
        local_path="pandas_profiling_report.html",
    )
